Allow using a custom docker-compose file when setting up e2e environment
This enables us to use the repositories' own docker-compose.custom.yml files in CI tests where some microservice might have pinned versions

diff --git a/.github/workflows/test-e2e-action.yml b/.github/workflows/test-e2e-action.yml
--- a/.github/workflows/test-e2e-action.yml
+++ b/.github/workflows/test-e2e-action.yml
@@ -61,6 +61,7 @@ jobs:
             mssqltestdb-docker-image:
             mapmatching-docker-image:
             mapmatchingdb-docker-image:
+            custom_docker_compose:
           # overwrite some
           - ui-docker-image: "hsldevcom/jore4-ui:latest"
             hasura-docker-image:
@@ -71,6 +72,18 @@ jobs:
             mssqltestdb-docker-image:
             mapmatching-docker-image:
             mapmatchingdb-docker-image:
+            custom_docker_compose:
+          # use custom docker-compose file
+          - ui-docker-image:
+            hasura-docker-image:
+            auth-docker-image:
+            mbtiles-docker-image:
+            jore3importer-docker-image:
+            testdb-docker-image:
+            mssqltestdb-docker-image:
+            mapmatching-docker-image:
+            mapmatchingdb-docker-image:
+            custom_docker_compose: "custom-compose.yml" # this overwrites the hasura image to be "jore4-hasura:latest"
 
     steps:
       - name: Checkout code
@@ -78,6 +91,13 @@ jobs:
 
       - name: Retrieve branch name
         uses: HSLdevcom/jore4-tools/github-actions/extract-metadata@extract-metadata-v1
+
+      - name: Create a temporary custom docker compose file for testing
+        run: |
+          touch custom-compose.yml
+          echo "services:" >> custom-compose.yml
+          echo "  jore4-hasura:" >> custom-compose.yml
+          echo "    image: 'hsldevcom/jore4-hasura:latest'" >> custom-compose.yml
 
       - name: start e2e env
         uses: ./github-actions/setup-e2e-environment
@@ -92,19 +112,34 @@ jobs:
           mssqltestdb_version: ${{ matrix.mssqltestdb-docker-image }}
           mapmatching_version: ${{ matrix.mapmatching-docker-image }}
           mapmatchingdb_version: ${{ matrix.mapmatchingdb-docker-image }}
+          custom_docker_compose: ${{ matrix.custom_docker_compose }}
 
       - name: Check that correct version of UI is running
         run: |
           UI_DEPLOYED_VERSION=`docker inspect --format='{{.Config.Image}}' ui`
-          if [[ "${{ matrix.ui-docker-image }}" == "" ]]
+          if [[ "${{ matrix.ui-docker-image }}" == "" && "$UI_DEPLOYED_VERSION" == "${{ matrix.ui-docker-image }}" ]]
           then
-            [[ "$UI_DEPLOYED_VERSION" != "${{ matrix.ui-docker-image }}" ]]
-          else
-            [[ "$UI_DEPLOYED_VERSION" == "${{ matrix.ui-docker-image }}" ]]
+            echo "Error! The docker image version shouldn't have been overwritten!"
+            exit 1
           fi
 
-      - name: Check that correct version of HASURA is running
-        # should not be :latest as it hasn't been overwritten
+          if [[ "${{ matrix.ui-docker-image }}" != "" && "$UI_DEPLOYED_VERSION" != "${{ matrix.ui-docker-image }}" ]]
+          then
+            echo "Error! The docker image version should've been overwritten!"
+            exit 1
+          fi
+
+      - name: Check that correct version of HASURA is running (overwritten by custom docker compose file)
         run: |
           HASURA_DEPLOYED_VERSION=`docker inspect --format='{{.Config.Image}}' hasura`
-          [[ "$HASURA_DEPLOYED_VERSION" != "hsldevcom/jore4-hasura:latest" ]]
+          if [[ "${{ matrix.custom_docker_compose }}" == "" && "$HASURA_DEPLOYED_VERSION" == "hsldevcom/jore4-hasura:latest" ]]
+          then
+            echo "Error! The docker image version shouldn't have been overwritten!"
+            exit 1
+          fi
+
+          if [[ "${{ matrix.custom_docker_compose }}" != "" && "$HASURA_DEPLOYED_VERSION" != "hsldevcom/jore4-hasura:latest" ]]
+          then
+            echo "Error! The docker image version should've been overwritten!"
+            exit 1
+          fi
